/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    conceptsSidebar: [{ type: "autogenerated", dirName: "concepts" }],
    apisSidebar: [
        {
            type: "doc",
            id: "apis/overall-concepts",
            label: "Overall Concepts",
        },
        {
            type: "category",
            label: "DemandHQ APIs",
            items: [
                {
                    type: "category",
                    label: "Demand API",
                    items: [
                        {
                            type: "doc",
                            label: "Concepts",
                            id: "apis/demandhq-apis/demand-api/concepts",
                        },
                    ],
                },
                {
                    type: "category",
                    label: "Storefront API",
                    items: [
                        {
                            type: "doc",
                            label: "Concepts",
                            id: "apis/demandhq-apis/storefront-api/concepts",
                        },
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Shared APIs",
            items: [
                {
                    type: "category",
                    label: "Events API",
                    items: [
                        {
                            type: "doc",
                            label: "Concepts",
                            id: "apis/shared-apis/events-api/concepts",
                        },
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Supplier APIs",
            items: [
                {
                    type: "category",
                    label: "Supply API",
                    items: [
                        {
                            type: "doc",
                            id: "apis/supplier-apis/supply-api/concepts",
                            label: "Concepts",
                        },
                        {
                            type: "category",
                            label: "Reference",
                            items: [
                                ...require("./docs/apis/supplier-apis/supply-api/reference/sidebar-schema.js")
                                    .schemaSidebar,
                            ],
                        },
                    ],
                },
            ],
        },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
